web:
  image: nginx:latest
  ports:
    - "8080:80"
    - "8443:443"
  volumes:
    - ./:/application
    - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    - ./.docker/nginx/localhost.crt:/etc/nginx/localhost.crt
    - ./.docker/nginx/localhost.key:/etc/nginx/localhost.key
  links:
    - php
php:
  build: ./.docker/php
  volumes:
    - ./:/application
  links:
    - db

adminer:
  image: adminer
  ports:
    - 8306:8080
  links:
    - db

db:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  ports:
    - 3307:3306
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=laravel
    - MYSQL_USER=laravel
    - MYSQL_PASSWORD=laravel

nodejs:
  image: wiwatsrt/docker-laravel-nodejs
  volumes:
    - ./:/var/www
